server:
  port: 8080
spring:
  datasource:
    # 数据源基本配置
    username: root
    password: zhang1989
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接池配置
    druid:
      initial-size: 5
      max-active: 50
      max-wait: 10000
      min-idle: 10
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: zhang1989

mybatis:
  mapper-locations: classpath:mapper/*/*/*Mapper.xml
  type-aliases-package: com.xyd.mcplat.*.*.entity



